#!/usr/bin/env bash
# Generate .env.local for local development, pulling the Supabase URL + API keys
# from the running local stack (`supabase status`). Reuses an existing AUTH_SECRET
# so restarts don't invalidate active sessions. Never overwrites a file that a
# developer has clearly customized beyond these managed keys.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
ENV_FILE="$ROOT/.env.local"

# Read the live local-stack values.
eval "$(cd "$ROOT" && supabase status -o env | sed 's/^/SUPA_/')"

# Preserve a previously generated AUTH_SECRET if one exists.
AUTH_SECRET=""
if [[ -f "$ENV_FILE" ]]; then
  AUTH_SECRET="$(grep -E '^AUTH_SECRET=' "$ENV_FILE" | head -1 | cut -d= -f2- || true)"
fi
[[ -n "$AUTH_SECRET" ]] || AUTH_SECRET="$(openssl rand -hex 32)"

cat > "$ENV_FILE" <<EOF
# Local development environment for 1500 Blueprint drills. Generated by
# .cursor/scripts/write-env-local.sh from the local Supabase stack.

# --- Supabase (local stack via \`supabase start\`) ---
NEXT_PUBLIC_SUPABASE_URL=${SUPA_API_URL}
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=${SUPA_PUBLISHABLE_KEY}
SUPABASE_SECRET_KEY=${SUPA_SECRET_KEY}

# --- App / auth ---
NEXT_PUBLIC_APP_URL=http://localhost:3000
AUTH_SECRET=${AUTH_SECRET}
# Dev-only login bypass (inert in production, which sets NODE_ENV=production).
# Sign in as either address with no password / Stripe / email round-trip.
# admin@example.com is also an admin (see ADMIN_EMAILS).
DEV_BYPASS_EMAILS=student@example.com,admin@example.com
ADMIN_EMAILS=admin@example.com
ADMIN_ACCESS_KEY=local-admin-key

# --- Optional external services (leave unset for offline local dev) ---
# ANTHROPIC_API_KEY=      # AI grading/generation drills (grammar/reading/ai-math)
# RESEND_API_KEY=         # magic-link emails (not needed with DEV_BYPASS_EMAILS)
# EMAIL_FROM=
# STRIPE_RESTRICTED_KEY=  # membership checks (bypassed via DEV_BYPASS_EMAILS)
EOF

echo "Wrote $ENV_FILE (Supabase URL ${SUPA_API_URL})."
